[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Serial monitor baud rate
monitor_speed = 115200

; Include secrets from header file
build_flags = 
    -include $PROJECT_DIR/src/secrets.h
